# Generated by Django 4.2.24 on 2025-09-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="会议标题")),
                (
                    "transcription",
                    models.JSONField(blank=True, default=list, verbose_name="会议记录内容"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="会议摘要")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voiceprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(max_length=100, verbose_name="说话人姓名"),
                ),
                ("embedding", models.JSONField(verbose_name="声纹向量")),
                (
                    "audio_filename",
                    models.CharField(blank=True, max_length=255, verbose_name="音频文件名"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
            ],
        ),
    ]
